### PR TITLE
Bug #239: fix lockscreen dimming

### PR DESCRIPTION
**Pull request by IBBoard**
I think I've managed to fix the lockscreen dimming (#239) and some related issues.

The commit messages have more detail, but basically:
* Gnome 46 seems to have changed one of the blur parameters
* The events were hooked up a little strangely and weren't applying consistently (or were applying repeatedly!) until I adjusted the setting change handling

I'm running this locally and I haven't seen any issues yet.

### CODE REVIEW

**Comment by IBBoard** [comment]
There may be a bug in this that I need to track down.

I've not worked out when. But sometimes it seems to use some default settings for the blur. I have it set for a slight blur, but sometimes when I wake the monitor and unlock it then I see a strong blur.

But at least it is blurring, so the prompts are easier to see 🙂

**Comment by neffo** [comment]
Thanks for looking into this, and yeah this has been a cause of some problems for a while. There is a bit of inconsistent behavior happening in the existing code which I never tracked down (seemed to trigger when recovering from standby as you note). I suspected this might be due to something that GNOME was doing during that state change, but I'll grant this code is ugly. Other extensions do this in other ways, but trying to tap into the state change of password entry is maybe unique? I think this is key to making it usable though.

**Comment by IBBoard** [comment]
After running this for a while, it's not 100% consistent, but it sometimes seems to go for a heavy blur, and it seems to be when I have to wake my monitor up (e.g. I've left my PC along for an hour or more). It's not every time. And it's not related to hibernating (the PC is still on, it's just the monitor going into power saving and then turning itself off). It could be a race condition during the wake up.

But the next lock after that has the right blur. And too much blur is better for readability than not enough blur, so I'm accepting the compromise for now 🙂

**Comment by neffo** [comment]
Yeah I had similar problems trying to debug this, not clear why it wasn't inconsistent.

Are you ready to merge it?

**Comment by neffo** [comment]
There's no rush, I just want to put out a version to support the new GNOME version with whatever is fixed. I've not tested your branch yet myself, but obviously appreciate the effort you've put into it and would be keen to merge when you are happy with it. (It can be merged whenever.)

**Comment by IBBoard** [comment]
If you want a version for Gnome support then merge this and I'll work on the the occasional default blur levels separately.

**Pull request merged**
