### PR TITLE
Version 38

### PR DESCRIPTION
**Pull request by neffo**
Changes in this version:

- [x] Updated German translation #142 #14
- [x] Updated Italian translation #143 #14
- [x] Updated Arabic translation #146 #14
- [x] Prevent incomplete images been stored #145 
- [ ] Is it possible to validate hashes of images #145, this could be done if we got the correct hashes from the JSON (we only get 1080p, not UHD)
- [x] When image folder is moved, the setting appears to revert to default #106
- [x] Migrate from Soup.SessionAsync (deprecated as of 2.42) #150
- [x] Better handle home folder relocations #151 
- [x] Some OSes (possibly Ubuntu 22.04 beta) don't expose GLib pictures folder, which can cause strange issues (null in folder names) #153
- [x] Fix preferences - they look a bit ugly in GTK4, in GNOME 42 the prefs window is slightly too small
- [ ] Fix gallery in GNOME 42 - can't scroll, or interact with/close window (currently disabled)
- [x] Set both light and dark style wallpapers in GNOME 42+ #153 
- [x] Bump extension version
- [x] Test on GNOME 3.36.9 (Ubuntu 20.04 LTS)
- [x] Test on GNOME 3.38 (Ubuntu 21.04)
- [x] Test on GNOME 42 (Ubuntu 22.04 beta and GNOME OS)

### CODE REVIEW

**Comment by bdaase** [comment]
I gave this a try on GNOME 42 (to see if it fixes https://github.com/neffo/bing-wallpaper-gnome-extension/issues/153), but this doesn't seem to work yet

```
Mär 14 20:03:20 p14s-gen2-amd gnome-shell[38824]: JS ERROR: TypeError: background is null
                                                   create_background_actor@/home/bjoern/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:101:9
                                                   update_backgrounds/<@/home/bjoern/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:92:35
                                                   update_backgrounds@/home/bjoern/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:91:37
                                                   enable/<@/home/bjoern/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/overview.js:26:18
                                                   destroy@resource:///org/gnome/shell/ui/background.js:721:34
                                                   _updateBackgrounds@resource:///org/gnome/shell/ui/layout.js:499:33
                                                   _prepareStartupAnimation@resource:///org/gnome/shell/ui/layout.js:717:24
                                                   _loadBackground/signalId</id<@resource:///org/gnome/shell/ui/layout.js:655:22
```

**Comment by neffo** [comment]
Thanks for testing Bjorn, but those errors seem to be generated by blur-my-shell? Is there a strange interaction occurring here that breaks wallpapers?

**Comment by bdaase** [comment]
Whoops, sorry, totally messed those up. 

I also tested with blur-my-shell disabled now, but the problem persists, the background image isn't set :/

**Comment by bdaase** [comment]
> All good, possibly related to the default image folder selection, GNOME 40 (or Glib) seems to do some things differently and I haven't properly tested the new code for handling it

Well, but it worked just fine with 41. So it must be something that changed from 41 to 42...

> If you haven't changed anything the defaults may have produced something that doesn't work.

Yeah, didn't change anything there.

> It should be '$HOME/Pictures/BingWallpaper' or equivalent for your locale, but this may get tripped up or may have carried over something from a previous install that has broken.

It is and the images get saved there just fine. But they don't get set as the background image.

**Comment by bdaase** [comment]
Alright, I think I know what's happening here now: The images are only set as the “Light” appearance wallpaper, but not as the “Dark” appearance one. That means, the extension currently works just fine if you have set the appearance style in gnome-control-center to “Light” but when set to “Dark”.

**Comment by bdaase** [comment]
I gave it a shot now and this fixes it for me 

```diff
diff --git a/extension.js b/extension.js
index aa20f00..eb14a01 100644
--- a/extension.js
+++ b/extension.js
@@ -55,11 +55,13 @@ function notifyError(msg) {
     Main.notifyError("BingWallpaper extension error", msg);
 }
 
-function doSetBackground(uri, schema) {
+function doSetBackground(uri, schema, set_dark) {
     let gsettings = new Gio.Settings({schema: schema});
     let prev = gsettings.get_string('picture-uri');
     uri = 'file://' + uri;
     gsettings.set_string('picture-uri', uri);
+    if (set_dark)
+        gsettings.set_string('picture-uri-dark', uri);
     Gio.Settings.sync();
     gsettings.apply();
     return (prev != uri); // return true if background uri has changed
@@ -257,11 +259,11 @@ class BingWallpaperIndicator extends PanelMenu.Button {
     }
 
     _setBackgroundDesktop() {
-        doSetBackground(this.filename, Utils.DESKTOP_SCHEMA);
+        doSetBackground(this.filename, Utils.DESKTOP_SCHEMA, true);
     }
     
     _setBackgroundScreensaver() {
-        doSetBackground(this.filename, Utils.LOCKSCREEN_SCHEMA);
+        doSetBackground(this.filename, Utils.LOCKSCREEN_SCHEMA, false);
     }
 
     _copyURLToClipboard() {
```

**Comment by neffo** [comment]
> Alright, I think I know what's happening here now: The images are only set as the “Light” appearance wallpaper, but not as the “Dark” appearance one. That means, the extension currently works just fine if you have set the appearance style in gnome-control-center to “Light” but when set to “Dark”.

Wasn't aware of this change, might not be exposed in Ubuntu 22.04 beta though (which I am using).

**Comment by bdaase** [comment]
> Wasn't aware of this change, might not be exposed in Ubuntu 22.04 beta though (which I am using).

That might very well be the case, and then the schema key also might not exist in Ubuntu 22.04. The above patch must then probably be guarded in some way...

**Pull request merged**
